apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  #  Below is actual config for POD --> Blueprint for POD
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ruchirnaphade/kubestack-frontend:latest
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webapp
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
    nodePort: 42000
