apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment  # Changed this name from webapp-deployment to mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: ruchirnaphade/kubestack-backend:latest
        ports:
        - containerPort: 5200
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGO_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGO_PASSWORD
        - name: MONGO_URI
          value: "mongodb+srv://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST)/?retryWrites=true&w=majority&appName=kubestack-cluster"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 5200
    targetPort: 5200

