apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ruchirnaphade/kubestack-frontend:latest
        ports:
        - containerPort: 4200
        env:
        - name: MONGO_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_USER
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_HOST
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_DB
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGO_PASSWORD
        - name: MONGO_URI
          value: "mongodb+srv://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST)/?retryWrites=true&w=majority&appName=kubestack-cluster"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
    nodePort: 31000

