name: Kubestack workflow
on:
  push:
    branches:
    - main

jobs:
  frontend:
    name: Build and containerize FE
    runs-on: self-hosted
    defaults:
      run:
        working-directory: frontend
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build FE
      run: npm run build

  backend:
    name: Build and containerize BE
    runs-on: self-hosted
    defaults:
      run:
        working-directory: backend/src
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
